#!/bin/bash
# Use rclone to sync dropbox with /home/tshmak/Dropbox/Apps/FanoTimMak

rclone copy dropbox: /home/tshmak/Dropbox/Apps/FanoTimMak/ --create-empty-src-dirs --dry-run
echo "" 

read -p "Ok?" yn
case $yn in
[Yy]* )
    rclone copy dropbox: /home/tshmak/Dropbox/Apps/FanoTimMak/ --create-empty-src-dirs
  ;;
* )
  exit
  ;;
esac
