#!/bin/bash
# # Usage: simlink_all_files /path/to/dir
# if [ ! -d "$1" ]; then
#     echo "Directory $1 DOES NOT exists."
#     exit 1
# fi
# for f in $(ls $1); do ln -s $1/$f $f ; done

# Usage simlink_all_files file1 [file2 ...]
targets=$(ls -d $@)
for i in $targets
do 
    ln -s $i 
done

