#!/bin/bash

currentdir=$(pwd)/
maccurrentdir=$(echo $currentdir | sed "s/^\/home/\/Users/") 
linuxcurrentdir=$(echo $currentdir | sed "s/^\/Users/\/home/")

if [ "$HOSTNAME" == "Timothys-MacBook-Pro.local" ]; then 
  remote=gpu1
  color="--color=auto"
  dir=$linuxcurrentdir
else 
  remote=mymac
  dir=$maccurrentdir
fi

ssh $remote "ls $color -Flha $dir"
