#!/bin/bash

if [ "$HOSTNAME" == "Timothys-MacBook-Pro.local" ]; then 
    currentdir=$(echo $(pwd) | sed "s/^\/Users/\/home/") 
  remote=gpu1
  color="--color=auto"
else 
    currentdir=$(echo $(pwd) | sed "s/^\/home/\/Users/") 
  remote=mymac
fi

ssh $remote "cd $currentdir; ls $color -Flha $1"
