#!/bin/bash

if "$1" == ""; then 
    dir=$(pwd)/
else
    dir=$1/
fi
macdir=$(echo $dir | sed "s/^\/home/\/Users/") 
linuxdir=$(echo $dir | sed "s/^\/Users/\/home/")

if [ "$HOSTNAME" == "Timothys-MacBook-Pro.local" ]; then 
  remote=gpu1
  color="--color=auto"
  DIR=$linuxdir
else 
  remote=mymac
  DIR=$macdir
fi

ssh $remote "ls $color -Flha $DIR"
