#!/bin/bash
wavfile=$1
server=${server:-kcgpu1}
shift
basename=$(basename $wavfile)
target=${KEEP:-/tmp/$basename}
[ "$KEEP" == "1" ] && target=/tmp/$basename
cmd="scp $server:$wavfile $target"
echo $cmd
$cmd
afplay "$@" $target
[ -z "$KEEP" ] && rm /tmp/$basename

