#!/bin/bash
wavfile=$1
server=${server:-kcgpu1}
shift
args=$@
basename=$(basename $wavfile)
#play=/usr/local/bin/play
play=/usr/bin/afplay
ap=$PWD/$wavfile
#rp=$(realpath $wavfile)
ext=${basename##*.}

ssh -t localhost -p 2222 "scp $server:$ap /tmp/sshplay.$ext && $play $args /tmp/sshplay.$ext && rm /tmp/sshplay.$ext"

