#!/bin/bash
wavfile=$1
server=${server:-sake}
shift
args=$@
basename=$(basename $wavfile)
#play=/usr/local/bin/play
play=/usr/bin/play
if [ "${wavfile:0:1}" = "/" ]
then
    ap=$wavfile
else
    ap=$PWD/$wavfile
fi
#rp=$(realpath $wavfile)
ext=${basename##*.}

ssh -t localhost -p 2222 "scp $server:$ap /tmp/sshplay.$ext && $play $args /tmp/sshplay.$ext && rm /tmp/sshplay.$ext"

