#!/bin/bash
pdffile=$1
server=${server:-gpu2}
shift
basename=$(basename $pdffile)
target=${KEEP:-/tmp/$basename}
[ "$KEEP" == "1" ] && target=/tmp/$basename
cmd="scp $server:$pdffile $target"
echo $cmd
$cmd
evince "$@" $target
[ -z "$KEEP" ] && rm /tmp/$basename

