#!/usr/bin/env python3
import os
import shutil

# home = '/Users/tshmak/'
home = os.path.expanduser('~/')
dropbox_folder = home + 'Dropbox/Apps/FanoTimMak/'
os.chdir(dropbox_folder)
synclist = '.synclist.txt'

with open(synclist, 'r') as f: 
    text = f.read()
    
files = text.split('\n')
for file in files: 
    # file = files[0]
    
    if len(file) == 0: 
        continue
    
    if file[0] == '#': 
        continue
    
    file2 = file.split()
    file = file2[0]
    if len(file2) > 1: 
        if len(file2) > 2: 
            print('%s ignored because the line has more than two columns.' % file)
            continue
        basename = file2[1]
    else: 
        basename = os.path.basename(file)    
    
    file = home + file
    dirname = os.path.dirname(file)
    exists = os.path.exists(file)
    existsdb = os.path.exists(basename)
    
    if (not exists) & (not existsdb): 
        print('%s does not exist in Dropbox or destination.' % (file))
    elif (not exists) & (existsdb): 
        if not os.path.isdir(dirname): 
            print('The directory %s does not exist' % dirname)
        else: 
            shutil.copy2(basename, file)
            print('%s copied from %s to %s' % (basename, 'Dropbox', dirname))
    elif (exists) & (not existsdb):
        shutil.copy2(file, '.')
        print('%s copied from %s to %s' % (basename, dirname, 'Dropbox'))
    elif (exists) & (existsdb): 
        mtime = os.path.getmtime(file)
        mtimedb = os.path.getmtime(basename)
        if mtime > mtimedb: 
            y = input('Overwrite %s in %s?' % (basename, 'Dropbox'))
            if len(y) > 0: 
                if y[0] == 'y' or 'Y': 
                    shutil.copy2(file, basename)
        elif mtime < mtimedb: 
            y = input('Overwrite %s in %s?' % (basename, dirname))
            if len(y) > 0: 
                if y[0] == 'y' or 'Y': 
                    shutil.copy2(basename, file)
        else: 
            print('%s is in sync' % (file))

        
            
                
            


